export const host="http://localhost:9000"
export const registerRoute=`${host}/api/auth/register`;
export const loginRoute=`${host}/api/auth/login`;
export const logoutRoute = `${host}/api/auth/logout`;
export const allUsersRoute = `${host}/api/auth/allusers`;
export const sendMessageRoute = `${host}/api/messages/addmsg`;
export const recieveMessageRoute = `${host}/api/messages/getmsg`;
export const setAvatarRoute = `${host}/api/auth/setavatar`;
export const getContactUsRoute=`${host}/api/contactus/getContactUs`;
export const setContactUsRoute=`${host}/api/contactus/setContactUs`;
export const getTodo=`${host}/api/kanban/getTodo`;
export const getBacklog=`${host}/api/kanban/getBacklog`;
export const getDone=`${host}/api/kanban/getDone`;
export const setTodo=`${host}/api/kanban/setTodo`;
export const setBacklog=`${host}/api/kanban/setBacklog`;
export const setDone=`${host}/api/kanban/setDone`;
export const deleteTodo=`${host}/api/kanban/deleteTodo`;
export const deleteBacklog=`${host}/api/kanban/deleteBacklog`;
export const deleteDone=`${host}/api/kanban/deleteDone`;
